// Package oas provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package oas

import (
	"context"
	"fmt"
	"net/url"
	"time"

	"github.com/gofiber/fiber/v3"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for Grain.
const (
	Month   Grain = "month"
	Quarter Grain = "quarter"
	Year    Grain = "year"
)

// Valid indicates whether the value is a known member of the Grain enum.
func (e Grain) Valid() bool {
	switch e {
	case Month:
		return true
	case Quarter:
		return true
	case Year:
		return true
	default:
		return false
	}
}

// Defines values for PnlLineKind.
const (
	Section PnlLineKind = "section"
	Total   PnlLineKind = "total"
)

// Valid indicates whether the value is a known member of the PnlLineKind enum.
func (e PnlLineKind) Valid() bool {
	switch e {
	case Section:
		return true
	case Total:
		return true
	default:
		return false
	}
}

// Defines values for PnlNodeDim.
const (
	Division PnlNodeDim = "division"
	SubItem  PnlNodeDim = "sub_item"
)

// Valid indicates whether the value is a known member of the PnlNodeDim enum.
func (e PnlNodeDim) Valid() bool {
	switch e {
	case Division:
		return true
	case SubItem:
		return true
	default:
		return false
	}
}

// Defines values for Role.
const (
	Cco          Role = "cco"
	Cfo          Role = "cfo"
	Coo          Role = "coo"
	DivisionHead Role = "division_head"
	Founder      Role = "founder"
)

// Valid indicates whether the value is a known member of the Role enum.
func (e Role) Valid() bool {
	switch e {
	case Cco:
		return true
	case Cfo:
		return true
	case Coo:
		return true
	case DivisionHead:
		return true
	case Founder:
		return true
	default:
		return false
	}
}

// Column defines model for Column.
type Column struct {
	From openapi_types.Date `json:"from"`

	// Key Example: 2026-03
	Key string `json:"key"`

	// Title Example: Мар 2026
	Title string `json:"title"`

	// To Не включительно.
	To openapi_types.Date `json:"to"`
}

// Error defines model for Error.
type Error struct {
	Message string `json:"message"`

	// Problems Нарушения проверки, по одному на пункт.
	Problems *[]string `json:"problems,omitempty"`
}

// Grain defines model for Grain.
type Grain string

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Login    string `json:"login"`
	Password string `json:"password"`
}

// Me defines model for Me.
type Me struct {
	Division *Ref `json:"division,omitempty"`

	// HasReport Отчёт доступен. false — роль не назначена или неизвестна (например,
	// viewer из старой таблицы бота): last_line тогда ничего не значит.
	HasReport bool  `json:"has_report"`
	Id        int64 `json:"id"`
	IsAdmin   bool  `json:"is_admin"`

	// LastLine Код последней видимой строки ОПиУ, включительно; null — все.
	LastLine *string `json:"last_line,omitempty"`
	Login    *string `json:"login,omitempty"`
	Role     Role    `json:"role"`
	Username *string `json:"username,omitempty"`
}

// Money Десятичная строка, точка, два знака.
//
// Example: -410997534.18
type Money = string

// PasswordSet defines model for PasswordSet.
type PasswordSet struct {
	Password string `json:"password"`
}

// PnlLine defines model for PnlLine.
type PnlLine struct {
	Children *[]PnlNode  `json:"children,omitempty"`
	Code     string      `json:"code"`
	Kind     PnlLineKind `json:"kind"`
	Title    string      `json:"title"`
	Values   []Money     `json:"values"`
}

// PnlLineKind defines model for PnlLine.Kind.
type PnlLineKind string

// PnlNode defines model for PnlNode.
type PnlNode struct {
	Children *[]PnlNode `json:"children,omitempty"`
	Dim      PnlNodeDim `json:"dim"`

	// Id null — значение не заполнено в листе.
	Id     *int32  `json:"id,omitempty"`
	Name   string  `json:"name"`
	Values []Money `json:"values"`
}

// PnlNodeDim defines model for PnlNode.Dim.
type PnlNodeDim string

// PnlReport defines model for PnlReport.
type PnlReport struct {
	Columns []Column `json:"columns"`

	// Incomplete Есть неразмеченные статьи — отчёт неполон.
	Incomplete bool        `json:"incomplete"`
	Lines      []PnlLine   `json:"lines"`
	Snapshot   SnapshotRef `json:"snapshot"`

	// Unmapped Только администратору.
	Unmapped *[]PnlUnmapped `json:"unmapped,omitempty"`
}

// PnlUnmapped defines model for PnlUnmapped.
type PnlUnmapped struct {
	// Item Пустая строка — проводки без статьи.
	Item   string  `json:"item"`
	Values []Money `json:"values"`
}

// Ref defines model for Ref.
type Ref struct {
	Id   int32  `json:"id"`
	Name string `json:"name"`
}

// Role defines model for Role.
type Role string

// Snapshot defines model for Snapshot.
type Snapshot struct {
	Id       int64     `json:"id"`
	RowCount int64     `json:"row_count"`
	TakenAt  time.Time `json:"taken_at"`
}

// SnapshotList defines model for SnapshotList.
type SnapshotList struct {
	// CurrentId Рабочая версия — новейшая непустая; null — данных нет.
	CurrentId *int64 `json:"current_id,omitempty"`

	// Items Новейшие первыми.
	Items []Snapshot `json:"items"`
}

// SnapshotRef defines model for SnapshotRef.
type SnapshotRef struct {
	Id int64 `json:"id"`

	// Stale Показан не новейший срез — последняя загрузка пустая.
	Stale   bool      `json:"stale"`
	TakenAt time.Time `json:"taken_at"`
}

// User defines model for User.
type User struct {
	BlockedAt   *time.Time `json:"blocked_at,omitempty"`
	CreatedAt   time.Time  `json:"created_at"`
	Division    *Ref       `json:"division,omitempty"`
	HasPassword *bool      `json:"has_password,omitempty"`
	Id          int64      `json:"id"`
	IsAdmin     bool       `json:"is_admin"`

	// LastSeenAt Последний запрос на сайте; null — не входил.
	LastSeenAt *time.Time `json:"last_seen_at,omitempty"`
	Login      *string    `json:"login,omitempty"`
	Role       Role       `json:"role"`
	TelegramId *int64     `json:"telegram_id,omitempty"`
	UpdatedAt  time.Time  `json:"updated_at"`
	Username   *string    `json:"username,omitempty"`
}

// UserCreate defines model for UserCreate.
type UserCreate struct {
	Blocked    bool    `json:"blocked"`
	DivisionId *int32  `json:"division_id,omitempty"`
	IsAdmin    bool    `json:"is_admin"`
	Login      *string `json:"login,omitempty"`

	// Password Обязателен, если задан login.
	Password   *string `json:"password,omitempty"`
	Role       Role    `json:"role"`
	TelegramId *int64  `json:"telegram_id,omitempty"`
	Username   *string `json:"username,omitempty"`
}

// UserUpdate defines model for UserUpdate.
type UserUpdate struct {
	Blocked    bool    `json:"blocked"`
	DivisionId *int32  `json:"division_id,omitempty"`
	IsAdmin    bool    `json:"is_admin"`
	Login      *string `json:"login,omitempty"`
	Role       Role    `json:"role"`
	TelegramId *int64  `json:"telegram_id,omitempty"`
	Username   *string `json:"username,omitempty"`
}

// UserID defines model for UserID.
type UserID = int64

// BadRequest defines model for BadRequest.
type BadRequest = Error

// Conflict defines model for Conflict.
type Conflict = Error

// Forbidden defines model for Forbidden.
type Forbidden = Error

// NotFound defines model for NotFound.
type NotFound = Error

// Unauthorized defines model for Unauthorized.
type Unauthorized = Error

// GetPnlParams defines parameters for GetPnl.
type GetPnlParams struct {
	Grain *Grain `form:"grain,omitempty" json:"grain,omitempty"`

	// Cols Колонки через запятую, не больше 12, все — выбранной гранулярности:
	// `2026-03` (месяц), `2026-Q1` (квартал), `2026` (год).
	// По умолчанию — последние 6 месяцев, включая текущий.
	Cols *[]string `form:"cols,omitempty" json:"cols,omitempty"`

	// Snapshot Версия среза; по умолчанию — рабочая (новейшая непустая).
	Snapshot *int64 `form:"snapshot,omitempty" json:"snapshot,omitempty"`
}

// CreateUserJSONRequestBody defines body for CreateUser for application/json ContentType.
type CreateUserJSONRequestBody = UserCreate

// UpdateUserJSONRequestBody defines body for UpdateUser for application/json ContentType.
type UpdateUserJSONRequestBody = UserUpdate

// SetUserPasswordJSONRequestBody defines body for SetUserPassword for application/json ContentType.
type SetUserPasswordJSONRequestBody = PasswordSet

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = LoginRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// ListDivisions Подразделения — для выбора у руководителя отдела
	// (GET /api/admin/divisions)
	ListDivisions(c fiber.Ctx) error
	// ListUsers Пользователи (только администратор)
	// (GET /api/admin/users)
	ListUsers(c fiber.Ctx) error
	// CreateUser Завести пользователя (только администратор)
	// (POST /api/admin/users)
	CreateUser(c fiber.Ctx) error
	// UpdateUser Изменить пользователя целиком (только администратор)
	// (PUT /api/admin/users/{id})
	UpdateUser(c fiber.Ctx, id UserID) error
	// SetUserPassword Задать пароль пользователю (только администратор)
	// (PUT /api/admin/users/{id}/password)
	SetUserPassword(c fiber.Ctx, id UserID) error
	// Login Вход по логину и паролю
	// (POST /api/auth/login)
	Login(c fiber.Ctx) error
	// Logout Выход — гасит текущую сессию
	// (POST /api/auth/logout)
	Logout(c fiber.Ctx) error
	// GetMe Текущий пользователь и его граница доступа
	// (GET /api/me)
	GetMe(c fiber.Ctx) error
	// GetPnl ОПиУ по колонкам одной гранулярности
	// (GET /api/pnl)
	GetPnl(c fiber.Ctx, params GetPnlParams) error
	// ListSnapshots Версии среза для селектора
	// (GET /api/snapshots)
	ListSnapshots(c fiber.Ctx) error
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []HandlerMiddlewareFunc
}

type MiddlewareFunc fiber.Handler
type HandlerMiddlewareFunc func(c fiber.Ctx, next fiber.Handler) error

// ListDivisions operation middleware
func (siw *ServerInterfaceWrapper) ListDivisions(c fiber.Ctx) error {

	handler := func(c fiber.Ctx) error {
		return siw.Handler.ListDivisions(c)
	}

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		m := siw.HandlerMiddlewares[i]
		next := handler
		handler = func(c fiber.Ctx) error {
			return m(c, next)
		}
	}

	return handler(c)
}

// ListUsers operation middleware
func (siw *ServerInterfaceWrapper) ListUsers(c fiber.Ctx) error {

	handler := func(c fiber.Ctx) error {
		return siw.Handler.ListUsers(c)
	}

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		m := siw.HandlerMiddlewares[i]
		next := handler
		handler = func(c fiber.Ctx) error {
			return m(c, next)
		}
	}

	return handler(c)
}

// CreateUser operation middleware
func (siw *ServerInterfaceWrapper) CreateUser(c fiber.Ctx) error {

	handler := func(c fiber.Ctx) error {
		return siw.Handler.CreateUser(c)
	}

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		m := siw.HandlerMiddlewares[i]
		next := handler
		handler = func(c fiber.Ctx) error {
			return m(c, next)
		}
	}

	return handler(c)
}

// UpdateUser operation middleware
func (siw *ServerInterfaceWrapper) UpdateUser(c fiber.Ctx) error {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id UserID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Params("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter id: %w", err).Error())
	}

	handler := func(c fiber.Ctx) error {
		return siw.Handler.UpdateUser(c, id)
	}

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		m := siw.HandlerMiddlewares[i]
		next := handler
		handler = func(c fiber.Ctx) error {
			return m(c, next)
		}
	}

	return handler(c)
}

// SetUserPassword operation middleware
func (siw *ServerInterfaceWrapper) SetUserPassword(c fiber.Ctx) error {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id UserID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Params("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter id: %w", err).Error())
	}

	handler := func(c fiber.Ctx) error {
		return siw.Handler.SetUserPassword(c, id)
	}

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		m := siw.HandlerMiddlewares[i]
		next := handler
		handler = func(c fiber.Ctx) error {
			return m(c, next)
		}
	}

	return handler(c)
}

// Login operation middleware
func (siw *ServerInterfaceWrapper) Login(c fiber.Ctx) error {

	handler := func(c fiber.Ctx) error {
		return siw.Handler.Login(c)
	}

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		m := siw.HandlerMiddlewares[i]
		next := handler
		handler = func(c fiber.Ctx) error {
			return m(c, next)
		}
	}

	return handler(c)
}

// Logout operation middleware
func (siw *ServerInterfaceWrapper) Logout(c fiber.Ctx) error {

	handler := func(c fiber.Ctx) error {
		return siw.Handler.Logout(c)
	}

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		m := siw.HandlerMiddlewares[i]
		next := handler
		handler = func(c fiber.Ctx) error {
			return m(c, next)
		}
	}

	return handler(c)
}

// GetMe operation middleware
func (siw *ServerInterfaceWrapper) GetMe(c fiber.Ctx) error {

	handler := func(c fiber.Ctx) error {
		return siw.Handler.GetMe(c)
	}

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		m := siw.HandlerMiddlewares[i]
		next := handler
		handler = func(c fiber.Ctx) error {
			return m(c, next)
		}
	}

	return handler(c)
}

// GetPnl operation middleware
func (siw *ServerInterfaceWrapper) GetPnl(c fiber.Ctx) error {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params GetPnlParams

	var query url.Values
	query, err = url.ParseQuery(string(c.Request().URI().QueryString()))
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for query string: %w", err).Error())
	}

	// ------------- Optional query parameter "grain" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "grain", query, &params.Grain, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter grain: %w", err).Error())
	}

	// ------------- Optional query parameter "cols" -------------

	err = runtime.BindQueryParameterWithOptions("form", false, false, "cols", query, &params.Cols, runtime.BindQueryParameterOptions{Type: "array", Format: ""})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter cols: %w", err).Error())
	}

	// ------------- Optional query parameter "snapshot" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "snapshot", query, &params.Snapshot, runtime.BindQueryParameterOptions{Type: "integer", Format: "int64"})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter snapshot: %w", err).Error())
	}

	handler := func(c fiber.Ctx) error {
		return siw.Handler.GetPnl(c, params)
	}

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		m := siw.HandlerMiddlewares[i]
		next := handler
		handler = func(c fiber.Ctx) error {
			return m(c, next)
		}
	}

	return handler(c)
}

// ListSnapshots operation middleware
func (siw *ServerInterfaceWrapper) ListSnapshots(c fiber.Ctx) error {

	handler := func(c fiber.Ctx) error {
		return siw.Handler.ListSnapshots(c)
	}

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		m := siw.HandlerMiddlewares[i]
		next := handler
		handler = func(c fiber.Ctx) error {
			return m(c, next)
		}
	}

	return handler(c)
}

// FiberServerOptions provides options for the Fiber server.
type FiberServerOptions struct {
	BaseURL            string
	Middlewares        []MiddlewareFunc
	HandlerMiddlewares []HandlerMiddlewareFunc
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router fiber.Router, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, FiberServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router fiber.Router, si ServerInterface, options FiberServerOptions) {
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.HandlerMiddlewares,
	}

	for _, m := range options.Middlewares {
		router.Use(fiber.Handler(m))
	}

	router.Post(options.BaseURL+"/api/auth/login", wrapper.Login)

	router.Post(options.BaseURL+"/api/auth/logout", wrapper.Logout)

	router.Get(options.BaseURL+"/api/me", wrapper.GetMe)

	router.Get(options.BaseURL+"/api/snapshots", wrapper.ListSnapshots)

	router.Get(options.BaseURL+"/api/pnl", wrapper.GetPnl)

	router.Get(options.BaseURL+"/api/admin/users", wrapper.ListUsers)

	router.Post(options.BaseURL+"/api/admin/users", wrapper.CreateUser)

	router.Put(options.BaseURL+"/api/admin/users/:id", wrapper.UpdateUser)

	router.Put(options.BaseURL+"/api/admin/users/:id/password", wrapper.SetUserPassword)

	router.Get(options.BaseURL+"/api/admin/divisions", wrapper.ListDivisions)

}

type BadRequestJSONResponse Error

type ConflictJSONResponse Error

type ForbiddenJSONResponse Error

type NotFoundJSONResponse Error

type UnauthorizedJSONResponse Error

type ListDivisionsRequestObject struct {
}

type ListDivisionsResponseObject interface {
	VisitListDivisionsResponse(ctx fiber.Ctx) error
}

type ListDivisions200JSONResponse []Ref

func (response ListDivisions200JSONResponse) VisitListDivisionsResponse(ctx fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(200)

	return ctx.JSON(&response)
}

type ListDivisions401JSONResponse struct{ UnauthorizedJSONResponse }

func (response ListDivisions401JSONResponse) VisitListDivisionsResponse(ctx fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(401)

	return ctx.JSON(&response)
}

type ListDivisions403JSONResponse struct{ ForbiddenJSONResponse }

func (response ListDivisions403JSONResponse) VisitListDivisionsResponse(ctx fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(403)

	return ctx.JSON(&response)
}

type ListUsersRequestObject struct {
}

type ListUsersResponseObject interface {
	VisitListUsersResponse(ctx fiber.Ctx) error
}

type ListUsers200JSONResponse []User

func (response ListUsers200JSONResponse) VisitListUsersResponse(ctx fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(200)

	return ctx.JSON(&response)
}

type ListUsers401JSONResponse struct{ UnauthorizedJSONResponse }

func (response ListUsers401JSONResponse) VisitListUsersResponse(ctx fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(401)

	return ctx.JSON(&response)
}

type ListUsers403JSONResponse struct{ ForbiddenJSONResponse }

func (response ListUsers403JSONResponse) VisitListUsersResponse(ctx fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(403)

	return ctx.JSON(&response)
}

type CreateUserRequestObject struct {
	Body *CreateUserJSONRequestBody
}

type CreateUserResponseObject interface {
	VisitCreateUserResponse(ctx fiber.Ctx) error
}

type CreateUser201JSONResponse User

func (response CreateUser201JSONResponse) VisitCreateUserResponse(ctx fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(201)

	return ctx.JSON(&response)
}

type CreateUser400JSONResponse struct{ BadRequestJSONResponse }

func (response CreateUser400JSONResponse) VisitCreateUserResponse(ctx fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(400)

	return ctx.JSON(&response)
}

type CreateUser401JSONResponse struct{ UnauthorizedJSONResponse }

func (response CreateUser401JSONResponse) VisitCreateUserResponse(ctx fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(401)

	return ctx.JSON(&response)
}

type CreateUser403JSONResponse struct{ ForbiddenJSONResponse }

func (response CreateUser403JSONResponse) VisitCreateUserResponse(ctx fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(403)

	return ctx.JSON(&response)
}

type CreateUser409JSONResponse struct{ ConflictJSONResponse }

func (response CreateUser409JSONResponse) VisitCreateUserResponse(ctx fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(409)

	return ctx.JSON(&response)
}

type UpdateUserRequestObject struct {
	Id   UserID `json:"id"`
	Body *UpdateUserJSONRequestBody
}

type UpdateUserResponseObject interface {
	VisitUpdateUserResponse(ctx fiber.Ctx) error
}

type UpdateUser200JSONResponse User

func (response UpdateUser200JSONResponse) VisitUpdateUserResponse(ctx fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(200)

	return ctx.JSON(&response)
}

type UpdateUser400JSONResponse struct{ BadRequestJSONResponse }

func (response UpdateUser400JSONResponse) VisitUpdateUserResponse(ctx fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(400)

	return ctx.JSON(&response)
}

type UpdateUser401JSONResponse struct{ UnauthorizedJSONResponse }

func (response UpdateUser401JSONResponse) VisitUpdateUserResponse(ctx fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(401)

	return ctx.JSON(&response)
}

type UpdateUser403JSONResponse struct{ ForbiddenJSONResponse }

func (response UpdateUser403JSONResponse) VisitUpdateUserResponse(ctx fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(403)

	return ctx.JSON(&response)
}

type UpdateUser404JSONResponse struct{ NotFoundJSONResponse }

func (response UpdateUser404JSONResponse) VisitUpdateUserResponse(ctx fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(404)

	return ctx.JSON(&response)
}

type UpdateUser409JSONResponse struct{ ConflictJSONResponse }

func (response UpdateUser409JSONResponse) VisitUpdateUserResponse(ctx fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(409)

	return ctx.JSON(&response)
}

type SetUserPasswordRequestObject struct {
	Id   UserID `json:"id"`
	Body *SetUserPasswordJSONRequestBody
}

type SetUserPasswordResponseObject interface {
	VisitSetUserPasswordResponse(ctx fiber.Ctx) error
}

type SetUserPassword204Response struct {
}

func (response SetUserPassword204Response) VisitSetUserPasswordResponse(ctx fiber.Ctx) error {
	ctx.Status(204)
	return nil
}

type SetUserPassword400JSONResponse struct{ BadRequestJSONResponse }

func (response SetUserPassword400JSONResponse) VisitSetUserPasswordResponse(ctx fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(400)

	return ctx.JSON(&response)
}

type SetUserPassword401JSONResponse struct{ UnauthorizedJSONResponse }

func (response SetUserPassword401JSONResponse) VisitSetUserPasswordResponse(ctx fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(401)

	return ctx.JSON(&response)
}

type SetUserPassword403JSONResponse struct{ ForbiddenJSONResponse }

func (response SetUserPassword403JSONResponse) VisitSetUserPasswordResponse(ctx fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(403)

	return ctx.JSON(&response)
}

type SetUserPassword404JSONResponse struct{ NotFoundJSONResponse }

func (response SetUserPassword404JSONResponse) VisitSetUserPasswordResponse(ctx fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(404)

	return ctx.JSON(&response)
}

type LoginRequestObject struct {
	Body *LoginJSONRequestBody
}

type LoginResponseObject interface {
	VisitLoginResponse(ctx fiber.Ctx) error
}

type Login200ResponseHeaders struct {
	SetCookie *string
}

type Login200JSONResponse struct {
	Body    Me
	Headers Login200ResponseHeaders
}

func (response Login200JSONResponse) VisitLoginResponse(ctx fiber.Ctx) error {
	if response.Headers.SetCookie != nil {
		ctx.Response().Header.Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(200)

	return ctx.JSON(&response.Body)
}

type Login400JSONResponse struct{ BadRequestJSONResponse }

func (response Login400JSONResponse) VisitLoginResponse(ctx fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(400)

	return ctx.JSON(&response)
}

type Login401JSONResponse struct{ UnauthorizedJSONResponse }

func (response Login401JSONResponse) VisitLoginResponse(ctx fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(401)

	return ctx.JSON(&response)
}

type Login429ResponseHeaders struct {
	RetryAfter *int
}

type Login429JSONResponse struct {
	Body    Error
	Headers Login429ResponseHeaders
}

func (response Login429JSONResponse) VisitLoginResponse(ctx fiber.Ctx) error {
	if response.Headers.RetryAfter != nil {
		ctx.Response().Header.Set("Retry-After", fmt.Sprint(*response.Headers.RetryAfter))
	}
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(429)

	return ctx.JSON(&response.Body)
}

type LogoutRequestObject struct {
}

type LogoutResponseObject interface {
	VisitLogoutResponse(ctx fiber.Ctx) error
}

type Logout204Response struct {
}

func (response Logout204Response) VisitLogoutResponse(ctx fiber.Ctx) error {
	ctx.Status(204)
	return nil
}

type Logout401JSONResponse struct{ UnauthorizedJSONResponse }

func (response Logout401JSONResponse) VisitLogoutResponse(ctx fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(401)

	return ctx.JSON(&response)
}

type GetMeRequestObject struct {
}

type GetMeResponseObject interface {
	VisitGetMeResponse(ctx fiber.Ctx) error
}

type GetMe200JSONResponse Me

func (response GetMe200JSONResponse) VisitGetMeResponse(ctx fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(200)

	return ctx.JSON(&response)
}

type GetMe401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetMe401JSONResponse) VisitGetMeResponse(ctx fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(401)

	return ctx.JSON(&response)
}

type GetPnlRequestObject struct {
	Params GetPnlParams
}

type GetPnlResponseObject interface {
	VisitGetPnlResponse(ctx fiber.Ctx) error
}

type GetPnl200JSONResponse PnlReport

func (response GetPnl200JSONResponse) VisitGetPnlResponse(ctx fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(200)

	return ctx.JSON(&response)
}

type GetPnl400JSONResponse struct{ BadRequestJSONResponse }

func (response GetPnl400JSONResponse) VisitGetPnlResponse(ctx fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(400)

	return ctx.JSON(&response)
}

type GetPnl401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetPnl401JSONResponse) VisitGetPnlResponse(ctx fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(401)

	return ctx.JSON(&response)
}

type GetPnl404JSONResponse struct{ NotFoundJSONResponse }

func (response GetPnl404JSONResponse) VisitGetPnlResponse(ctx fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(404)

	return ctx.JSON(&response)
}

type ListSnapshotsRequestObject struct {
}

type ListSnapshotsResponseObject interface {
	VisitListSnapshotsResponse(ctx fiber.Ctx) error
}

type ListSnapshots200JSONResponse SnapshotList

func (response ListSnapshots200JSONResponse) VisitListSnapshotsResponse(ctx fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(200)

	return ctx.JSON(&response)
}

type ListSnapshots401JSONResponse struct{ UnauthorizedJSONResponse }

func (response ListSnapshots401JSONResponse) VisitListSnapshotsResponse(ctx fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(401)

	return ctx.JSON(&response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// ListDivisions Подразделения — для выбора у руководителя отдела
	// (GET /api/admin/divisions)
	ListDivisions(ctx context.Context, request ListDivisionsRequestObject) (ListDivisionsResponseObject, error)
	// ListUsers Пользователи (только администратор)
	// (GET /api/admin/users)
	ListUsers(ctx context.Context, request ListUsersRequestObject) (ListUsersResponseObject, error)
	// CreateUser Завести пользователя (только администратор)
	// (POST /api/admin/users)
	CreateUser(ctx context.Context, request CreateUserRequestObject) (CreateUserResponseObject, error)
	// UpdateUser Изменить пользователя целиком (только администратор)
	// (PUT /api/admin/users/{id})
	UpdateUser(ctx context.Context, request UpdateUserRequestObject) (UpdateUserResponseObject, error)
	// SetUserPassword Задать пароль пользователю (только администратор)
	// (PUT /api/admin/users/{id}/password)
	SetUserPassword(ctx context.Context, request SetUserPasswordRequestObject) (SetUserPasswordResponseObject, error)
	// Login Вход по логину и паролю
	// (POST /api/auth/login)
	Login(ctx context.Context, request LoginRequestObject) (LoginResponseObject, error)
	// Logout Выход — гасит текущую сессию
	// (POST /api/auth/logout)
	Logout(ctx context.Context, request LogoutRequestObject) (LogoutResponseObject, error)
	// GetMe Текущий пользователь и его граница доступа
	// (GET /api/me)
	GetMe(ctx context.Context, request GetMeRequestObject) (GetMeResponseObject, error)
	// GetPnl ОПиУ по колонкам одной гранулярности
	// (GET /api/pnl)
	GetPnl(ctx context.Context, request GetPnlRequestObject) (GetPnlResponseObject, error)
	// ListSnapshots Версии среза для селектора
	// (GET /api/snapshots)
	ListSnapshots(ctx context.Context, request ListSnapshotsRequestObject) (ListSnapshotsResponseObject, error)
}

type StrictHandlerFunc func(ctx fiber.Ctx, args any) (any, error)

type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// ListDivisions operation middleware
func (sh *strictHandler) ListDivisions(ctx fiber.Ctx) error {
	var request ListDivisionsRequestObject

	handler := func(ctx fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.ListDivisions(ctx.Context(), request.(ListDivisionsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListDivisions")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(ListDivisionsResponseObject); ok {
		if err := validResponse.VisitListDivisionsResponse(ctx); err != nil {
			return err
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// ListUsers operation middleware
func (sh *strictHandler) ListUsers(ctx fiber.Ctx) error {
	var request ListUsersRequestObject

	handler := func(ctx fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.ListUsers(ctx.Context(), request.(ListUsersRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListUsers")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(ListUsersResponseObject); ok {
		if err := validResponse.VisitListUsersResponse(ctx); err != nil {
			return err
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// CreateUser operation middleware
func (sh *strictHandler) CreateUser(ctx fiber.Ctx) error {
	var request CreateUserRequestObject

	var body CreateUserJSONRequestBody
	if err := ctx.Bind().Body(&body); err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	}
	request.Body = &body

	handler := func(ctx fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.CreateUser(ctx.Context(), request.(CreateUserRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateUser")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(CreateUserResponseObject); ok {
		if err := validResponse.VisitCreateUserResponse(ctx); err != nil {
			return err
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// UpdateUser operation middleware
func (sh *strictHandler) UpdateUser(ctx fiber.Ctx, id UserID) error {
	var request UpdateUserRequestObject

	request.Id = id

	var body UpdateUserJSONRequestBody
	if err := ctx.Bind().Body(&body); err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	}
	request.Body = &body

	handler := func(ctx fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateUser(ctx.Context(), request.(UpdateUserRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateUser")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(UpdateUserResponseObject); ok {
		if err := validResponse.VisitUpdateUserResponse(ctx); err != nil {
			return err
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// SetUserPassword operation middleware
func (sh *strictHandler) SetUserPassword(ctx fiber.Ctx, id UserID) error {
	var request SetUserPasswordRequestObject

	request.Id = id

	var body SetUserPasswordJSONRequestBody
	if err := ctx.Bind().Body(&body); err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	}
	request.Body = &body

	handler := func(ctx fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.SetUserPassword(ctx.Context(), request.(SetUserPasswordRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "SetUserPassword")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(SetUserPasswordResponseObject); ok {
		if err := validResponse.VisitSetUserPasswordResponse(ctx); err != nil {
			return err
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// Login operation middleware
func (sh *strictHandler) Login(ctx fiber.Ctx) error {
	var request LoginRequestObject

	var body LoginJSONRequestBody
	if err := ctx.Bind().Body(&body); err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	}
	request.Body = &body

	handler := func(ctx fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.Login(ctx.Context(), request.(LoginRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Login")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(LoginResponseObject); ok {
		if err := validResponse.VisitLoginResponse(ctx); err != nil {
			return err
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// Logout operation middleware
func (sh *strictHandler) Logout(ctx fiber.Ctx) error {
	var request LogoutRequestObject

	handler := func(ctx fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.Logout(ctx.Context(), request.(LogoutRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Logout")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(LogoutResponseObject); ok {
		if err := validResponse.VisitLogoutResponse(ctx); err != nil {
			return err
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetMe operation middleware
func (sh *strictHandler) GetMe(ctx fiber.Ctx) error {
	var request GetMeRequestObject

	handler := func(ctx fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.GetMe(ctx.Context(), request.(GetMeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetMe")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetMeResponseObject); ok {
		if err := validResponse.VisitGetMeResponse(ctx); err != nil {
			return err
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetPnl operation middleware
func (sh *strictHandler) GetPnl(ctx fiber.Ctx, params GetPnlParams) error {
	var request GetPnlRequestObject

	request.Params = params

	handler := func(ctx fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.GetPnl(ctx.Context(), request.(GetPnlRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetPnl")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetPnlResponseObject); ok {
		if err := validResponse.VisitGetPnlResponse(ctx); err != nil {
			return err
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// ListSnapshots operation middleware
func (sh *strictHandler) ListSnapshots(ctx fiber.Ctx) error {
	var request ListSnapshotsRequestObject

	handler := func(ctx fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.ListSnapshots(ctx.Context(), request.(ListSnapshotsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListSnapshots")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(ListSnapshotsResponseObject); ok {
		if err := validResponse.VisitListSnapshotsResponse(ctx); err != nil {
			return err
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}
